FROM golang:1.17.8 as intermediate
RUN mkdir /app
ADD . /app
WORKDIR /app
COPY go.mod go.sum ./
COPY . .

RUN apt-get update -y
RUN apt-get install -y libvips

RUN cd cmd/back && CGO_CFLAGS_ALLOW=-Xpreprocessor go build -o main .

FROM golang:1.17.8

RUN mkdir /app

WORKDIR /app

COPY --from=intermediate /app/cmd/back/main /app
COPY --from=intermediate /app/configs/config-back.yml /app/configs/

RUN apt-get update -y
RUN apt-get install -y libvips

CMD ["/app/main"]

